In [347]:
import pandas as pd

In [348]:
df=pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\corn_data.csv")

In [349]:
df.head()

,County,Farmer,Education,Gender,Age bracket,Household size,Crop,Acreage,Fertilizer amount,Laborers,Yield,Power source,Water source,Main credit source,Crop insurance,Farm records,Main advisory source,Extension provider,Advisory format,Advisory language,Latitude,Longitude
0,TAITA TAVETA,fmr_65,Certificate,Male,36-45,7,corn,2.00,50,2,300,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.46,38.35
1,TAITA TAVETA,fmr_77,Certificate,Male,36-45,7,corn,0.25,50,2,270,Manual,Rain,Credit groups,No,Yes,Radio,County Government,SMS text,Kiswahili,-3.31,38.40
2,TAITA TAVETA,fmr_89,Certificate,Male,36-45,7,corn,3.00,251,2,270,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.41,38.37
3,TAITA TAVETA,fmr_102,Certificate,Male,36-45,7,corn,1.50,300,3,200,Manual,Rain,Credit groups,No,Yes,Radio,County Government,SMS text,Kiswahili,-3.39,38.37
4,TAITA TAVETA,fmr_25,Certificate,Male,46-55,3,corn,NaN,50,2,180,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.39,38.33

In [350]:
df['Crop insurance'].value_counts()

Crop insurance
No    422
Name: count, dtype: int64

In [351]:
df.shape

(422, 22)

In [352]:
pd.set_option('display.max_columns',None)

In [353]:
df=pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\corn_data.csv")

In [354]:
df.head()

,County,Farmer,Education,Gender,Age bracket,Household size,Crop,Acreage,Fertilizer amount,Laborers,Yield,Power source,Water source,Main credit source,Crop insurance,Farm records,Main advisory source,Extension provider,Advisory format,Advisory language,Latitude,Longitude
0,TAITA TAVETA,fmr_65,Certificate,Male,36-45,7,corn,2.00,50,2,300,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.46,38.35
1,TAITA TAVETA,fmr_77,Certificate,Male,36-45,7,corn,0.25,50,2,270,Manual,Rain,Credit groups,No,Yes,Radio,County Government,SMS text,Kiswahili,-3.31,38.40
2,TAITA TAVETA,fmr_89,Certificate,Male,36-45,7,corn,3.00,251,2,270,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.41,38.37
3,TAITA TAVETA,fmr_102,Certificate,Male,36-45,7,corn,1.50,300,3,200,Manual,Rain,Credit groups,No,Yes,Radio,County Government,SMS text,Kiswahili,-3.39,38.37
4,TAITA TAVETA,fmr_25,Certificate,Male,46-55,3,corn,NaN,50,2,180,Manual,Rain,Credit groups,No,Yes,Radio,Private Provider,Phone Calls,Vernacular,-3.39,38.33

In [355]:
df['Power source']=df['Power source'].astype(str)

In [356]:
df=df.drop(columns=['County','Farmer','Main credit source','Farm records','Advisory format','Advisory language','Power source','Water source','Crop insurance'])

In [357]:
df.head()

,Education,Gender,Age bracket,Household size,Crop,Acreage,Fertilizer amount,Laborers,Yield,Main advisory source,Extension provider,Latitude,Longitude
0,Certificate,Male,36-45,7,corn,2.00,50,2,300,Radio,Private Provider,-3.46,38.35
1,Certificate,Male,36-45,7,corn,0.25,50,2,270,Radio,County Government,-3.31,38.40
2,Certificate,Male,36-45,7,corn,3.00,251,2,270,Radio,Private Provider,-3.41,38.37
3,Certificate,Male,36-45,7,corn,1.50,300,3,200,Radio,County Government,-3.39,38.37
4,Certificate,Male,46-55,3,corn,NaN,50,2,180,Radio,Private Provider,-3.39,38.33

In [358]:
df['Acreage'].fillna(0,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_16532\1894385298.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Acreage'].fillna(0,inplace=True)

In [359]:
df.head(5)

,Education,Gender,Age bracket,Household size,Crop,Acreage,Fertilizer amount,Laborers,Yield,Main advisory source,Extension provider,Latitude,Longitude
0,Certificate,Male,36-45,7,corn,2.00,50,2,300,Radio,Private Provider,-3.46,38.35
1,Certificate,Male,36-45,7,corn,0.25,50,2,270,Radio,County Government,-3.31,38.40
2,Certificate,Male,36-45,7,corn,3.00,251,2,270,Radio,Private Provider,-3.41,38.37
3,Certificate,Male,36-45,7,corn,1.50,300,3,200,Radio,County Government,-3.39,38.37
4,Certificate,Male,46-55,3,corn,0.00,50,2,180,Radio,Private Provider,-3.39,38.33

In [360]:
x=df.iloc[:,[0,1,2,3,4,5,6,7,10,11,12,13,14]].values

IndexError: positional indexers are out-of-bounds

In [ ]:
y=df.iloc[:,[8]].values
y

array([[300],
       [270],
       [270],
       [200],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [150],
       [150],
       [135],
       [135],
       [125],
       [180],
       [160],
       [100],
       [100],
       [100],
       [ 90],
       [ 90],
       [ 90],
       [ 75],
       [ 50],
       [ 50],
       [540],
       [540],
       [450],
       [450],
       [360],
       [360],
       [360],
       [360],
       [180],
       [150],
       [100],
       [ 90],
       [ 90],
       [ 50],
       [600],
       [560],
       [550],
       [540],
       [540],
       [540],
       [540],
       [540],
       [540],
       [540],
       [540],
       [500],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [440],
       [400],
       [400],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [330],
       [330],
       [330],
       [330],
       [330],
       [330],
       [300],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [250],
       [250],
       [250],
       [250],
       [250],
       [250],
       [250],
       [240],
       [220],
       [200],
       [200],
       [200],
       [200],
       [200],
       [200],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [160],
       [160],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [135],
       [135],
       [135],
       [126],
       [115],
       [110],
       [110],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [ 95],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 80],
       [ 80],
       [ 80],
       [ 80],
       [ 80],
       [ 80],
       [ 78],
       [ 75],
       [ 70],
       [ 70],
       [ 60],
       [ 60],
       [ 60],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [600],
       [550],
       [550],
       [540],
       [540],
       [500],
       [500],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [450],
       [400],
       [400],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [360],
       [330],
       [330],
       [330],
       [330],
       [330],
       [330],
       [330],
       [330],
       [300],
       [300],
       [300],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [270],
       [250],
       [250],
       [200],
       [200],
       [200],
       [200],
       [200],
       [200],
       [200],
       [200],
       [200],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [180],
       [160],
       [160],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [150],
       [135],
       [120],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [100],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 90],
       [ 70],
       [ 70],
       [ 50],
       [ 50],
       [ 50],
       [ 50],
       [540],
       [540],
       [450],
       [450],
       [450],
       [360],
       [360],
       [360],
       [330],
       [300],
       [270],
       [270],
       [270],
       [270],
       [270],
       [220],
       [200],
       [200],
       [180],
       [180],
       [180],
       [160],
       [150],
       [110],
       [100],
       [ 90]])

In [ ]:
x

array([['Certificate', 'Male', '36-45', ..., 'Private Provider', -3.46,
        38.35],
       ['Certificate', 'Male', '36-45', ..., 'County Government', -3.31,
        38.4],
       ['Certificate', 'Male', '36-45', ..., 'Private Provider', -3.41,
        38.37],
       ...,
       [nan, 'Female', '46-55', ..., 'County Government', -3.41, 38.35],
       [nan, 'Male', '46-55', ..., 'County Government', -3.56, 38.6],
       [nan, 'Male', '46-55', ..., 'Private Provider', -3.41, 38.37]],
      shape=(422, 13), dtype=object)

In [ ]:
df.head()

,Education,Gender,Age bracket,Household size,Crop,Acreage,Fertilizer amount,Laborers,Yield,Water source,Crop insurance,Main advisory source,Extension provider,Latitude,Longitude
0,Certificate,Male,36-45,7,corn,2.00,50,2,300,Rain,No,Radio,Private Provider,-3.46,38.35
1,Certificate,Male,36-45,7,corn,0.25,50,2,270,Rain,No,Radio,County Government,-3.31,38.40
2,Certificate,Male,36-45,7,corn,3.00,251,2,270,Rain,No,Radio,Private Provider,-3.41,38.37
3,Certificate,Male,36-45,7,corn,1.50,300,3,200,Rain,No,Radio,County Government,-3.39,38.37
4,Certificate,Male,46-55,3,corn,0.00,50,2,180,Rain,No,Radio,Private Provider,-3.39,38.33

In [ ]:
from sklearn.preprocessing import LabelEncoder
le0 = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()
le4 = LabelEncoder()
# le9 = LabelEncoder()
le10 = LabelEncoder()
le11 = LabelEncoder()
le12 = LabelEncoder()
le13 = LabelEncoder()

# Fit and transform each column with its dedicated encoder
x[:, 0] = le0.fit_transform(x[:, 0])
x[:, 1] = le1.fit_transform(x[:, 1])
x[:, 2] = le2.fit_transform(x[:, 2])
x[:, 4] = le4.fit_transform(x[:, 4])
# x[:, 9] = le9.fit_transform(x[:, 9])
x[:, 10] = le10.fit_transform(x[:, 10])
x[:, 11] = le11.fit_transform(x[:, 11])
x[:, 12] = le12.fit_transform(x[:, 12])

x

array([[0, 1, 1, ..., 3, 14, 8],
       [0, 1, 1, ..., 0, 29, 13],
       [0, 1, 1, ..., 3, 19, 10],
       ...,
       [5, 0, 2, ..., 0, 19, 8],
       [5, 1, 2, ..., 0, 4, 22],
       [5, 1, 2, ..., 3, 19, 10]], shape=(422, 13), dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

ValueError: could not convert string to float: 'No'